path_X_train: "/home/app/src/data/pre_process/X_train.pkl"
path_X_test: "/home/app/src/data/pre_process/X_test.pkl"
path_y_train: "/home/app/src/data/pre_process/y_train.pkl"
path_y_test: "/home/app/src/data/pre_process/y_test.pkl"


# The following part has to be modified with the training ML model you want

path_to_save: "/home/app/src/trained_models/catboost"

model: "catboost"     # Here you can choose between: catboost, lightgbm, randomforest, xgboost and ensemble

hyperparameter_grid:
    eval_metric: ["AUC"]
    random_state: [64]
    depth: [4, 6, 8, 10]
    learning_rate: [0.01, 0.03, 0.06, 0.1]
    max_leaves: [16, 31, 46]
