path_X_train: "/home/app/src/data/pre_process/X_train.pkl"
path_X_test: "/home/app/src/data/pre_process/X_test.pkl"
path_y_train: "/home/app/src/data/pre_process/y_train.pkl"
path_y_test: "/home/app/src/data/pre_process/y_test.pkl"


# The following part has to be modified with the training ML model you want

path_to_save: "/home/app/src/trained_models/randomforest"

model: "randomforest"     # Here you can choose between: catboost, lightgbm, randomforest, xgboost and ensemble

hyperparameter_grid:
    n_jobs: [-1]
    random_state: [64]
    bootstrap: [True, False]
    max_depth: [10, 50, 100, None]
    min_samples_leaf: [1, 2, 4]
    min_samples_split: [2, 5, 10]
