path_X_train: "/home/app/src/data/pre_process/X_train.pkl"
path_X_test: "/home/app/src/data/pre_process/X_test.pkl"
path_y_train: "/home/app/src/data/pre_process/y_train.pkl"
path_y_test: "/home/app/src/data/pre_process/y_test.pkl"


# The following part has to be modified with the training ML model you want

path_to_save: "/home/app/src/trained_models/xgboost"

model: "xgboost"     # Here you can choose between: catboost, lightgbm, randomforest, xgboost and ensemble

hyperparameter_grid:
    n_jobs: [-1]
    random_state: [64]
    learning_rate: [0.05, 0.10, 0.2, 0.3]
    max_depth: [3, 7, 12, 19]
    min_child_weight: [1, 3, 5, 7]
    gamma: [0, 0.2, 0.4]
